In [23]:
import pandas as pd
import numpy as np

In [24]:
# Save path to data set in a variable
data_file_1 = "complete_events_lat_lng_MSP.csv"

In [25]:
# Use Pandas to read data:
event_df = pd.read_csv(data_file_1)

In [26]:
#gives you the top 5 rows of the file
event_df

,state,city,event_name,group_name,attendees,lat,lng,category,venue_event_link,event_street,Google_Map_Link,event_lat,event_lng,address
0,NJ,Aberdeern,All are welcome to join us OR email: breakthro...,Your BREAKTHROUGH is right around the corner!,0,40.167060,-74.499870,Beliefs,https://www.meetup.com/New-Church-in-the-neigh...,95 Cambridge Drive,https://www.google.com/maps/search/?api=1&quer...,39.813165,-75.166758,"""95 Cambridge Drive Aberdeern, NJ"""
1,NJ,Aberdeern,All are welcome to join us OR email: breakthro...,Your BREAKTHROUGH is right around the corner!,0,40.167060,-74.499870,Beliefs,https://www.meetup.com/New-Church-in-the-neigh...,95 Cambridge Drive,https://www.google.com/maps/search/?api=1&quer...,39.813165,-75.166758,"""95 Cambridge Drive Aberdeern, NJ"""
2,NJ,Bellmawr,"Bachata Vs Salsa @ The Stardust, w/ DJ BigBoy ...",Social and Like Dancing - Philly,4,39.867613,-75.094618,Dance,https://www.meetup.com/phillysocialmeetup/even...,363 W Browning Rd,https://www.google.com/maps/search/?api=1&quer...,39.869579,-75.094949,"""363 W Browning Rd Bellmawr, NJ"""
3,NJ,Bernardsville,Brighthelm D&D Campaign â€¢ First Session On Us!,Gaming Meetups at The Bearded Dragon Games,1,40.718680,-74.569227,Sci-Fi & Games,https://www.meetup.com/Gaming-Meetups-at-The-B...,123 Claremont Road,https://www.google.com/maps/search/?api=1&quer...,40.723554,-74.573557,"""123 Claremont Road Bernardsville, NJ"""
4,NJ,Bordentown,Winter Hike At Crystal Lake,DelawareRiverHikers,14,40.146221,-74.711826,Outdoors & Adventure,https://www.meetup.com/delawareriverhikers/eve...,2401 Axe Factory Rd,https://www.google.com/maps/search/?api=1&quer...,40.116715,-74.728546,"""2401 Axe Factory Rd Bordentown, NJ"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,PA,Yardley,Join us for Breakfast and bring plenty of Busi...,LeTip of Newtown,1,40.245664,-74.845997,Career & Business,https://www.meetup.com/LeTip-of-Newtown/events...,82 East Afton Avenue,https://www.google.com/maps/search/?api=1&quer...,40.244540,-74.836710,"""82 East Afton Avenue Yardley, PA"""
1052,PA,Yardley,Letip of Newtown,Philly Biz Connects,1,40.245664,-74.845997,Career & Business,https://www.meetup.com/phillybizconnects/event...,82 E Afton Ave,https://www.google.com/maps/search/?api=1&quer...,40.244540,-74.836710,"""82 E Afton Ave Yardley, PA"""
1053,PA,York,Using Lightroom Classic with the Cloud by Juli...,York County Camera Club,20,39.962398,-76.727392,Photography,https://www.meetup.com/York-County-Camera-Club...,123 at home avenue,https://www.google.com/maps/search/?api=1&quer...,39.966245,-76.720725,"""123 at home avenue York, PA"""
1054,PA,York,Big Jim's Seafood House - Come to the Garden,York Christian Fiction Books Meetup Group,2,39.962398,-76.727392,Book Clubs,https://www.meetup.com/york-christian-fiction-...,2252 Industrial Hwy,https://www.google.com/maps/search/?api=1&quer...,39.978155,-76.684296,"""2252 Industrial Hwy York, PA"""
1055,PA,York,Real Estate Investors of York January Goal Set...,Real Estate Investors of York,23,39.962398,-76.727392,Career & Business,https://www.meetup.com/Real-Estate-Investors-o...,2000 Loucks Rd,https://www.google.com/maps/search/?api=1&quer...,39.973763,-76.774973,"""2000 Loucks Rd York, PA"""

In [27]:
#event_df = event_df.loc[event_df['state'] == event_df["event_state"]]
#event_df

In [28]:
event_df.dropna(axis =0, inplace = True)
event_df = event_df.drop_duplicates(subset = ["state","city", "event_name"])

In [29]:
event_df.head(529)

,state,city,event_name,group_name,attendees,lat,lng,category,venue_event_link,event_street,Google_Map_Link,event_lat,event_lng,address
0,NJ,Aberdeern,All are welcome to join us OR email: breakthro...,Your BREAKTHROUGH is right around the corner!,0,40.167060,-74.499870,Beliefs,https://www.meetup.com/New-Church-in-the-neigh...,95 Cambridge Drive,https://www.google.com/maps/search/?api=1&quer...,39.813165,-75.166758,"""95 Cambridge Drive Aberdeern, NJ"""
2,NJ,Bellmawr,"Bachata Vs Salsa @ The Stardust, w/ DJ BigBoy ...",Social and Like Dancing - Philly,4,39.867613,-75.094618,Dance,https://www.meetup.com/phillysocialmeetup/even...,363 W Browning Rd,https://www.google.com/maps/search/?api=1&quer...,39.869579,-75.094949,"""363 W Browning Rd Bellmawr, NJ"""
3,NJ,Bernardsville,Brighthelm D&D Campaign â€¢ First Session On Us!,Gaming Meetups at The Bearded Dragon Games,1,40.718680,-74.569227,Sci-Fi & Games,https://www.meetup.com/Gaming-Meetups-at-The-B...,123 Claremont Road,https://www.google.com/maps/search/?api=1&quer...,40.723554,-74.573557,"""123 Claremont Road Bernardsville, NJ"""
4,NJ,Bordentown,Winter Hike At Crystal Lake,DelawareRiverHikers,14,40.146221,-74.711826,Outdoors & Adventure,https://www.meetup.com/delawareriverhikers/eve...,2401 Axe Factory Rd,https://www.google.com/maps/search/?api=1&quer...,40.116715,-74.728546,"""2401 Axe Factory Rd Bordentown, NJ"""
5,NJ,Bordentown,"""Dr. UFO presents ... """,FRINGE New Jersey,3,40.146221,-74.711826,Beliefs,https://www.meetup.com/FRINGEnewjersey/events/...,18 E. Union Street,https://www.google.com/maps/search/?api=1&quer...,40.143566,-74.707891,"""18 E. Union Street Bordentown, NJ"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,PA,Yardley,Letip of Newtown,Philly Biz Connects,1,40.245664,-74.845997,Career & Business,https://www.meetup.com/phillybizconnects/event...,82 E Afton Ave,https://www.google.com/maps/search/?api=1&quer...,40.244540,-74.836710,"""82 E Afton Ave Yardley, PA"""
1050,PA,Yardley,Wednesday evening - Gentle Yoga Class,Yardley Rec Board,1,40.245664,-74.845997,Sports & Fitness,https://www.meetup.com/Yardley-Rec-Board/event...,56 South Main Street,https://www.google.com/maps/search/?api=1&quer...,40.245664,-74.845997,"""56 South Main Street Yardley, PA"""
1053,PA,York,Using Lightroom Classic with the Cloud by Juli...,York County Camera Club,20,39.962398,-76.727392,Photography,https://www.meetup.com/York-County-Camera-Club...,123 at home avenue,https://www.google.com/maps/search/?api=1&quer...,39.966245,-76.720725,"""123 at home avenue York, PA"""
1054,PA,York,Big Jim's Seafood House - Come to the Garden,York Christian Fiction Books Meetup Group,2,39.962398,-76.727392,Book Clubs,https://www.meetup.com/york-christian-fiction-...,2252 Industrial Hwy,https://www.google.com/maps/search/?api=1&quer...,39.978155,-76.684296,"""2252 Industrial Hwy York, PA"""
1055,PA,York,Real Estate Investors of York January Goal Set...,Real Estate Investors of York,23,39.962398,-76.727392,Career & Business,https://www.meetup.com/Real-Estate-Investors-o...,2000 Loucks Rd,https://www.google.com/maps/search/?api=1&quer...,39.973763,-76.774973,"""2000 Loucks Rd York, PA"""

In [30]:
event_df['city'].head()
#Find all instances of a value and replace
#bottleking_df["price"] = bottleking_df["price"].str.replace("$", "").astype(float)

0        Aberdeern
2         Bellmawr
3    Bernardsville
4       Bordentown
5       Bordentown
Name: city, dtype: object

In [31]:
test1 = event_df.groupby(['state','city','lat','lng']).size().reset_index().rename(columns = {0:'count'})
test2 = test1.reset_index()
test2
test3 = test2.rename(columns={"index": 'city_id'})
test3 = test3.drop(["count"], axis= "columns")
test3

     city_id state           city        lat        lng
0          0    NJ      Aberdeern  40.167060 -74.499870
1          1    NJ       Bellmawr  39.867613 -75.094618
2          2    NJ  Bernardsville  40.718680 -74.569227
3          3    NJ     Bordentown  40.146221 -74.711826
4          4    NJ      Bridgeton  39.427337 -75.234077
..       ...   ...            ...        ...        ...
212      212    PA      Whitehall  40.657478 -75.507465
213      213    PA     Wyomissing  40.329537 -75.965212
214      214    PA        Yardley  40.245664 -74.845997
215      215    PA           York  39.962398 -76.727392
216      216    PA     johnstown   40.326741 -78.921970

[217 rows x 5 columns]

In [32]:
#test3.to_csv('msptest.csv', encoding='utf-8', index=False)

In [34]:
duplicateRowsDF = test3[test3.duplicated(keep='first')]
duplicateRowsDF.head()

Empty DataFrame
Columns: [city_id, state, city, lat, lng]
Index: []

In [40]:
test3.drop_duplicates(subset = ['lat','lng'])
test3

     city_id state           city        lat        lng
0          0    NJ      Aberdeern  40.167060 -74.499870
1          1    NJ       Bellmawr  39.867613 -75.094618
2          2    NJ  Bernardsville  40.718680 -74.569227
3          3    NJ     Bordentown  40.146221 -74.711826
4          4    NJ      Bridgeton  39.427337 -75.234077
..       ...   ...            ...        ...        ...
212      212    PA      Whitehall  40.657478 -75.507465
213      213    PA     Wyomissing  40.329537 -75.965212
214      214    PA        Yardley  40.245664 -74.845997
215      215    PA           York  39.962398 -76.727392
216      216    PA     johnstown   40.326741 -78.921970

[217 rows x 5 columns]

In [39]:
counts = test3.nunique ()
print(counts)

city_id    217
state        3
city       216
lat        206
lng        206
dtype: int64

In [42]:
test3.city.unique()

array(['Aberdeern', 'Bellmawr', 'Bernardsville', 'Bordentown',
       'Bridgeton', 'Bridgewater', 'Caldwell', 'Camden', 'Chatham',
       'Cherry Hill', 'Chesterfield ', 'Clifton', 'Collingswood',
       'Columbia', 'Cranford', 'Edison', 'Edison ', 'Fair Lawn',
       'Fairfield', 'Fairview', 'Garfield', 'Garwood', 'Hackensack',
       'Hamilton', 'Hamilton Township', 'Hardwick', 'Hardwick Township',
       'Hasbrouck Heights', 'Hillsborough Township', 'Hoboken',
       'Hoboken ', 'Jersey City', 'Lafayette', 'Lawrence Township',
       'Lodi', 'Lyndhurst', 'Madison', 'Maplewood', 'Matawan', 'Maywood',
       'Merchantville', 'Metuchen', 'Milltown', 'Millville', 'Milmay',
       'Monroe Township', 'Montclair', 'Mountainside', 'New Brunswick',
       'Newark', 'Newfoundland', 'Newton', 'North Bergen', 'Nutley',
       'Old Bridge', 'Old Bridge Township', 'Palmyra', 'Paramus',
       'Parlin', 'Parsippany', 'Pennsauken ', 'Pennsauken Township',
       'Piscataway', 'Pittsgrove', 'Princeton', 'Rahway', 'Ridgewood',
       'Robbinsville Twp', 'Roselle', 'Runnemede', 'Rutherford',
       'Secaucus', 'Skillman', 'Somerset', 'South Amboy',
       'South Plainfield', 'South River', 'Teaneck', 'Titusville',
       'Trenton', 'UNION CITY', 'Union', 'Vauxhall', 'Vernon Township',
       'Voorhees', 'Warren', 'West Orange', 'Willingboro', 'Woodbridge',
       'edison', 'Albany', 'Amherst', 'Astoria', 'Ballston',
       'Ballston Lake', 'Bay Shore', 'Binghamton', 'Bolton Landing',
       'Brentwood', 'Bronxville', 'Brooklyn', 'Brooklyn ', 'Buffalo',
       'Buffalo ', 'Clifton Park', 'Colonie', 'Deer Park', 'Dobbs Ferry',
       'Elmira', 'Fairport', 'Farmingdale', 'Glens Falls', 'Great River',
       'Hastings-On-Hudson', 'Huntington', 'Islandia', 'Ithaca',
       'Kingston', 'Lake Grove', 'Lake Ronkonkoma', 'Larchmont', 'Latham',
       'Lindenhurst', 'Malta', 'Manhattan', 'Manhattan, New York',
       'Middletown', 'Mount Vernon', 'NY', 'NYC', 'New Paltz', 'New York',
       'New York ', 'North White Plains', 'Nyack', 'Online', 'Pittsford',
       'Pleasant Valley', 'Pleasantville', 'Port Chester', 'Poughkeepsie',
       'Queens', 'Riverdale, Bronx', 'Rochester', 'Sands Point',
       'Saratoga Springs', 'Saugerties', 'Schenectady', 'Smithtown',
       'Smithtown ', 'Snyder', 'St James', 'Staten Island', 'Stony Brook',
       'Syracuse', 'TBA', 'TBD', 'Tappan', 'Tonawanda', 'Troy',
       'WHITESTONE', 'Wappingers Falls', 'West Babylon',
       'Westchester County', 'White Plains', 'Williamsville', 'Yonkers',
       'Allentown', 'Bala Cynwyd', 'Bensalem', 'Boyertown ', 'Bristol',
       'Bucks County', 'Camp Hill', 'Catasauqua', 'Douglassville',
       'East Stroudsburg', 'Erie', 'Fairless Hills', 'Glenside',
       'Hanover', 'Harrisburg', 'Hellertown', 'Horsham',
       'Huntingdon Valley, Pa 19006', 'Johnstown', 'Lancaster',
       'Langhorne', 'Lebanon', 'Leola', 'Levittown ', 'Limerick',
       'Morrisville', 'Munhall', 'Narberth', 'Newtown',
       'North Versailles', 'Pennsylvania', 'Philadelphia',
       'Philadelphia ', 'Phoenixville', 'Pittsburgh', 'Pottstown',
       'Richboro', 'Spring City', 'State College', 'Stevens', 'Stowe',
       'Stroudsburg', 'Verona', 'West Pittston', 'Whitehall',
       'Wyomissing', 'Yardley', 'York', 'johnstown '], dtype=object)

In [ ]:
test3.to_csv('msptest.csv', encoding='utf-8', index=False)

In [ ]:
new_df = pd.merge(event_df, test3, how='left', left_on=[ 'state', 'city', 'lat', 'lng'], right_on = [ 'state', 'city','lat', 'lng'])
new_df
new_df = new_df.drop([ 'state', 'city', 'lat', 'lng'] , axis ="columns")
new_df['city_id'] = new_df['city_id'].astype(int)
new_df

In [ ]:
#test3 = test3.drop(["event_city"], axis = 'columns')
#test3

In [ ]:
test3

In [ ]:
test3.to_csv('region.csv', encoding='utf-8', index=False)

In [ ]:
new_df.to_csv('events.csv', encoding='utf-8', index=False)

In [ ]:
import re

In [ ]:
def strip_character(dataCol):
    r = re.compile(r'[^a-zA-Z !@#$%&*_+-=|\:";<>,./()[\]{}\']')
    return r.sub('', dataCol)

datafile="events.csv"
datafile_df=pd.read_csv(datafile)
pd.set_option("display.max_row", None, "display.max_columns", None)
datafile_df["event_name"] = datafile_df["event_name"].apply(strip_character)
datafile_df["group_name"] = datafile_df["group_name"].apply(strip_character)
datafile_df["venue_event_link"] = datafile_df["venue_event_link"].apply(strip_character)
datafile_df["Google_Map_Link"] = datafile_df["Google_Map_Link"].apply(strip_character)
datafile_df["event_street"] = datafile_df["event_street"].apply(strip_character)
datafile_df["address"] = datafile_df["address"].str.strip(';"')
#datafile_df = datafile_df.rename(columns={'Unnamed:':'id'})
#datafile_df = datafile_df.drop(['Unnamed'])
datafile_df.to_csv("events.csv",index=False)
datafile_df